// Generated by `wit-bindgen` 0.17.0. DO NOT EDIT!
#ifndef __BINDINGS_EXAMPLE_H
#define __BINDINGS_EXAMPLE_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

// Exported Functions from `example`
uint32_t example_run(uint32_t k);

#ifdef __cplusplus
}
#endif
#endif
