// Generated by `wit-bindgen` 0.16.0. DO NOT EDIT!
pub mod component {
  pub mod proxy {
    
    #[allow(clippy::all)]
    pub mod proxy {
      #[used]
      #[doc(hidden)]
      #[cfg(target_arch = "wasm32")]
      static __FORCE_SECTION_REF: fn() = super::super::super::__link_section;
      #[allow(unused_unsafe, clippy::all)]
      pub fn middleware(k: u32,) -> u32{
        
        #[allow(unused_imports)]
        use wit_bindgen::rt::{alloc, vec::Vec, string::String};
        unsafe {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "component:proxy/proxy")]
          extern "C" {
            #[link_name = "middleware"]
            fn wit_import(_: i32, ) -> i32;
          }
          
          #[cfg(not(target_arch = "wasm32"))]
          fn wit_import(_: i32, ) -> i32{ unreachable!() }
          let ret = wit_import(wit_bindgen::rt::as_i32(k));
          ret as u32
        }
      }
      
    }
    
  }
}
pub mod exports {
  pub mod user {
    pub mod fib {
      
      #[allow(clippy::all)]
      pub mod run {
        #[used]
        #[doc(hidden)]
        #[cfg(target_arch = "wasm32")]
        static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_section;
        const _: () = {
          
          #[doc(hidden)]
          #[export_name = "user:fib/run#run"]
          #[allow(non_snake_case)]
          unsafe extern "C" fn __export_run(arg0: i32,) -> i32 {
            #[allow(unused_imports)]
            use wit_bindgen::rt::{alloc, vec::Vec, string::String};
            
            // Before executing any other code, use this function to run all static
            // constructors, if they have not yet been run. This is a hack required
            // to work around wasi-libc ctors calling import functions to initialize
            // the environment.
            //
            // This functionality will be removed once rust 1.69.0 is stable, at which
            // point wasi-libc will no longer have this behavior.
            //
            // See
            // https://github.com/bytecodealliance/preview2-prototyping/issues/99
            // for more details.
            #[cfg(target_arch="wasm32")]
            wit_bindgen::rt::run_ctors_once();
            
            let result0 = <_GuestImpl as Guest>::run(arg0 as u32);
            wit_bindgen::rt::as_i32(result0)
          }
        };
        use super::super::super::super::super::Component as _GuestImpl;
        pub trait Guest {
          fn run(k: u32,) -> u32;
        }
        
      }
      
    }
  }
}

#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:fib"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 280] = [3, 0, 3, 102, 105, 98, 0, 97, 115, 109, 13, 0, 1, 0, 7, 39, 1, 65, 2, 1, 66, 2, 1, 64, 1, 1, 107, 121, 0, 121, 4, 0, 3, 114, 117, 110, 1, 0, 4, 1, 12, 117, 115, 101, 114, 58, 102, 105, 98, 47, 114, 117, 110, 5, 0, 11, 9, 1, 0, 3, 114, 117, 110, 3, 0, 0, 7, 111, 1, 65, 2, 1, 65, 4, 1, 66, 2, 1, 64, 1, 1, 107, 121, 0, 121, 4, 0, 10, 109, 105, 100, 100, 108, 101, 119, 97, 114, 101, 1, 0, 3, 1, 21, 99, 111, 109, 112, 111, 110, 101, 110, 116, 58, 112, 114, 111, 120, 121, 47, 112, 114, 111, 120, 121, 5, 0, 1, 66, 2, 1, 64, 1, 1, 107, 121, 0, 121, 4, 0, 3, 114, 117, 110, 1, 0, 4, 1, 12, 117, 115, 101, 114, 58, 102, 105, 98, 47, 114, 117, 110, 5, 1, 4, 1, 12, 117, 115, 101, 114, 58, 102, 105, 98, 47, 102, 105, 98, 4, 0, 11, 9, 1, 0, 3, 102, 105, 98, 3, 2, 0, 0, 16, 12, 112, 97, 99, 107, 97, 103, 101, 45, 100, 111, 99, 115, 0, 123, 125, 0, 70, 9, 112, 114, 111, 100, 117, 99, 101, 114, 115, 1, 12, 112, 114, 111, 99, 101, 115, 115, 101, 100, 45, 98, 121, 2, 13, 119, 105, 116, 45, 99, 111, 109, 112, 111, 110, 101, 110, 116, 6, 48, 46, 49, 56, 46, 50, 16, 119, 105, 116, 45, 98, 105, 110, 100, 103, 101, 110, 45, 114, 117, 115, 116, 6, 48, 46, 49, 54, 46, 48];

#[inline(never)]
#[doc(hidden)]
#[cfg(target_arch = "wasm32")]
pub fn __link_section() {}
