package example:host

interface http-api{
    record req{
        headers:string,
        footer:string
    }
    getheader: func() -> u32
}

world host{
    export bar : interface{
        record req{
            headers:string,
        }
        getheader: func() -> u32
    }

    import run: func(n : u32)->u32


    export execute: func(n : u32)->u32
}